### PR TITLE
Fix cssmin bug that affects Safari and Firefox

### PR DESCRIPTION
**Pull request by thegreatsunra**
cssmin will combine the `html` and `:host` declarations if they are adjacent to one another. Safari and Firefox do not understand `:host` natively, so they will ignore any ruleset that contains a `:host`.

This change makes sure the `html` font-family declaration gets applied in all browsers.

### CODE REVIEW

**Comment by thegreatsunra** [comment]
Any word on this?

**Comment by mdwragg** [comment]
Hi @thegreatsunra have you tested recompiling any of the px components sass with this change in? Do things still work as expected if so? Thanks.

**Comment by thegreatsunra** [comment]
@mdwragg Happy to help. How should I go about recompiling and testing a px component with this change?

**Comment by mdwragg** [comment]
Hi @thegreatsunra - can you do the following so we can accept this PR:
- up the `package.json` patch version
- same for `bower.json`
- tag for same minor version

...And we'll get the ball rolling. Thanks for the PR.

**Comment by thegreatsunra** [comment]
Excellent. I'll give it a shot, @mdwragg!

**Comment by thegreatsunra** [comment]
Okay, should be good to merge now.

**Comment by mdwragg** [comment]
Excellent - thanks @thegreatsunra!

**Comment by mdwragg** [comment]
Tested in components via `bower link` -ing the PR version and recompiling Sass. Typography still behaved as expected 👍

**Comment by thegreatsunra** [comment]
💯

**Pull request merged**
